export const quotes = [
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "It always seems impossible until it's done. - Nelson Mandela",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "Act as if what you do makes a difference. It does. - William James",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",

  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
  "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
  "Whether you think you can or you think you can't, you're right. - Henry Ford",
  "Perfection is not attainable, but if we chase perfection we can catch excellence. - Vince Lombardi",
  "Life is 10% what happens to me and 90% of how I react to it. - Charles Swindoll",
  "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough. - Oprah Winfrey",
  "None of us is as smart as all of us. - Ken Blanchard",
  "I can't change the direction of the wind, but I can adjust my sails to always reach my destination. - Jimmy Dean",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine",
  "If you want to make your dreams come true, the first thing you have to do is wake up. - J.M. Power",
  "I am not a product of my circumstances. I am a product of my decisions. - Stephen Covey",
  "The most common way people give up their power is by thinking they don't have any. - Alice Walker",
  "The mind is everything. What you think you become. - Buddha",
  "The best revenge is massive success. - Frank Sinatra",
  "People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily. - Zig Ziglar",
  "Life shrinks or expands in proportion to one's courage. - Anais Nin",
  "If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced. - Vincent Van Gogh",
  "There is only one way to avoid criticism: do nothing, say nothing, and be nothing. - Aristotle",
  "Ask yourself if what you're doing today is getting you closer to where you want to be tomorrow. - Unknown",
  "The two most important days in your life are the day you are born and the day you find out why. - Mark Twain",
  "Happiness is not something readymade. It comes from your own actions. - Dalai Lama",
  "You miss 100% of the shots you don't take. - Wayne Gretzky",
  "The difference between ordinary and extraordinary is that little extra. - Jimmy Johnson",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
]
